export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  CUSTOMER: 'CUSTOMER',
  FLORIST: 'FLORIST',
  GARDENER: 'GARDENER',
});

export const PERMISSIONS = Object.freeze({
  MANAGE_USERS: 'MANAGE_USERS',
  MANAGE_ROLES: 'MANAGE_ROLES',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  MANAGE_PRODUCTS: 'MANAGE_PRODUCTS',
  MANAGE_INVENTORY: 'MANAGE_INVENTORY',
  MANAGE_ORDERS: 'MANAGE_ORDERS',
  MANAGE_DELIVERY: 'MANAGE_DELIVERY',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  USE_CHATBOT: 'USE_CHATBOT',
  USE_RECOMMENDATIONS: 'USE_RECOMMENDATIONS',
  MANAGE_PROFILE: 'MANAGE_PROFILE',
});
